# Simple perceptron program

In [14]:
import numpy as np
import os

#### 1. Load in the dataset

In [15]:
DATASET_DIR = "./dataset"
TESTSET_DIR = "./testset"

In [16]:
dataset_files = os.listdir(DATASET_DIR)
testset_files = os.listdir(TESTSET_DIR)

In [17]:
print(
    f"Dataset file count: {len(dataset_files)}",
    f"Testset file count: {len(testset_files)}",
    sep="\n"
)

Dataset file count: 21
Testset file count: 7


In [18]:
print(
    open(f"./dataset/{dataset_files[3]}", "r").read()
)

................................
................................
................................
................................
................................
................................
................................
..............##................
............######..............
...........########.............
..........##########............
..........##########............
.........############...........
.........############...........
..........##########............
..........##########............
...........########.............
............######..............
..............##................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........

#### 2. Convert the dataset into numbers

In [19]:
# String to numbers
def ston(string):
    return np.array([(ord(c)**4)/10000000 for c in string])

In [20]:
dataset = []
testset = []

for file in dataset_files:
    pixels = open(f"./dataset/{file}", "r").read().replace("\n", "")
    # If filename is rect-n.txt that means it is a rectangle
    is_rect = True if file.split("-")[0] == "rect" else False
    dataset.append((
        ston(pixels),
        is_rect
    ))

for file in testset_files:
    pixels = open(f"./testset/{file}", "r").read().replace("\n", "")
    # If filename is rect-n.txt that means it is a rectangle
    is_rect = True if file.split("-")[0] == "rect" else False
    testset.append((
        ston(pixels),
        is_rect
    ))

In [21]:
dataset, testset

([(array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   True),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477

#### 3. Define the neural network

In [22]:
class LayerDense():
    def __init__(self, inputs, neurons):
        self.weights = np.random.randn(inputs) * 0.001
        self.biases = np.random.randn(neurons) * 0.001
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class ActivationSigmoid():
    def forward(self, x):
        self.output = 1 / (1 + np.exp(-x))
    
    def backward(self, x):
        self.output = x * (1 - x)

In [23]:
layer1 = LayerDense(32 * 32, 1)
activation1 = ActivationSigmoid()

#### 4. Train the neural network

In [24]:
inputs, labels = zip(*dataset)
learning_rate = 0.5

for iteration in range(10_000):
    for input, label in zip(inputs, labels):
        layer1.forward(input)
        activation1.forward(layer1.output)
        prediction = activation1.output
        
        loss = label - prediction
        activation1.backward(prediction)
        adjustments = loss * activation1.output
        
        layer1.weights += learning_rate * adjustments * input
        layer1.biases += learning_rate * adjustments
    
    # We dont want 10000 lines of output
    # print(f"Iteration: {iteration + 1}, Loss: {loss}")

#### 5. Test the neural network

In [25]:
inputs, labels = zip(*testset)
predictions = []

for input, label in zip(inputs, labels):
    layer1.forward(input)
    activation1.forward(layer1.output)
    prediction = activation1.output
    predictions.append(np.round(prediction[0]))

print(np.array(predictions, dtype=np.int32))
print(np.array(labels, dtype=np.int32))
accuracy = np.mean(np.array(predictions) == np.array(labels)) * 100

print(f"Accuracy: {accuracy:.2f}%")

[1 0 0 0 0 0 0]
[1 0 0 0 0 1 1]
Accuracy: 71.43%
