# Simple perceptron program

In [251]:
import numpy as np
import os

#### 1. Load in the dataset

In [252]:
DATASET_DIR = "./dataset"
TESTSET_DIR = "./testset"

In [253]:
dataset_files = os.listdir(DATASET_DIR)
testset_files = os.listdir(TESTSET_DIR)

In [254]:
print(
    f"Dataset file count: {len(dataset_files)}",
    f"Testset file count: {len(testset_files)}",
    sep="\n"
)

Dataset file count: 21
Testset file count: 7


In [255]:
print(
    open(f"./dataset/{dataset_files[3]}", "r").read()
)

................................
................................
................................
................................
................................
................................
................................
..............##................
............######..............
...........########.............
..........##########............
..........##########............
.........############...........
.........############...........
..........##########............
..........##########............
...........########.............
............######..............
..............##................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........

#### 2. Convert the dataset into numbers

In [256]:
# String to numbers
def ston(string):
    return np.array([(ord(c)**4)/10000000 for c in string])

In [257]:
dataset = []
testset = []

for file in dataset_files:
    pixels = open(f"./dataset/{file}", "r").read().replace("\n", "")
    # If filename is rect-n.txt that means it is a rectangle
    is_rect = True if file.split("-")[0] == "rect" else False
    dataset.append((
        ston(pixels),
        is_rect
    ))

for file in testset_files:
    pixels = open(f"./testset/{file}", "r").read().replace("\n", "")
    # If filename is rect-n.txt that means it is a rectangle
    is_rect = True if file.split("-")[0] == "rect" else False
    testset.append((
        ston(pixels),
        is_rect
    ))

In [258]:
dataset, testset

([(array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   True),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477456,
          0.4477456]),
   False),
  (array([0.4477456, 0.4477456, 0.4477456, ..., 0.4477456, 0.4477

#### 3. Define the neural network

In [259]:
class LayerDense():
    def __init__(self, inputs, neurons):
        self.weights = np.random.randn(inputs) * 0.001
        self.biases = np.random.randn(neurons) * 0.001
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class ActivationSigmoid():
    def forward(self, x):
        self.output = 1 / (1 + np.exp(-x))
    
    def backward(self, x):
        self.output = x * (1 - x)

In [260]:
layer1 = LayerDense(32 * 32, 1)
activation1 = ActivationSigmoid()

#### 4. Train the neural network

In [261]:
inputs, labels = zip(*dataset)
learning_rate = 0.5

for iteration in range(10_000):
    for input, label in zip(inputs, labels):
        layer1.forward(input)
        activation1.forward(layer1.output)
        prediction = activation1.output
        
        loss = label - prediction
        activation1.backward(prediction)
        adjustments = loss * activation1.output
        
        layer1.weights += learning_rate * adjustments * input
        layer1.biases += learning_rate * adjustments
    
    print(f"Iteration: {iteration + 1}, Loss: {loss}")

Iteration: 1, Loss: [0.99999562]
Iteration: 2, Loss: [0.99999556]
Iteration: 3, Loss: [0.9999955]
Iteration: 4, Loss: [0.99999544]
Iteration: 5, Loss: [0.99999538]
Iteration: 6, Loss: [0.99999532]
Iteration: 7, Loss: [0.99999525]
Iteration: 8, Loss: [0.99999518]
Iteration: 9, Loss: [0.99999512]
Iteration: 10, Loss: [0.99999505]
Iteration: 11, Loss: [0.99999497]
Iteration: 12, Loss: [0.9999949]
Iteration: 13, Loss: [0.99999482]
Iteration: 14, Loss: [0.99999475]
Iteration: 15, Loss: [0.99999466]
Iteration: 16, Loss: [0.99999458]
Iteration: 17, Loss: [0.9999945]
Iteration: 18, Loss: [0.99999441]
Iteration: 19, Loss: [0.99999432]
Iteration: 20, Loss: [0.99999422]
Iteration: 21, Loss: [0.99999413]
Iteration: 22, Loss: [0.99999403]
Iteration: 23, Loss: [0.99999392]
Iteration: 24, Loss: [0.99999382]
Iteration: 25, Loss: [0.99999371]
Iteration: 26, Loss: [0.99999359]
Iteration: 27, Loss: [0.99999348]
Iteration: 28, Loss: [0.99999335]
Iteration: 29, Loss: [0.99999323]
Iteration: 30, Loss: [0.99

#### 5. Test the neural network

In [262]:
inputs, labels = zip(*testset)
predictions = []

for input, label in zip(inputs, labels):
    layer1.forward(input)
    activation1.forward(layer1.output)
    prediction = activation1.output
    predictions.append(np.round(prediction[0]))

print(np.array(predictions, dtype=np.int32))
print(np.array(labels, dtype=np.int32))
accuracy = np.mean(np.array(predictions) == np.array(labels)) * 100

print(f"Accuracy: {accuracy:.2f}%")

[1 0 0 0 0 0 0]
[1 0 0 0 0 1 1]
Accuracy: 71.43%
